# -*- coding: utf-8 -*-
"""Covid-19 Analysis and Visualization using Plotly Express.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CVmzQ00TAYswgH-0GcOZO5csWuxKcP5v
"""

import numpy as np;
import pandas as pd;

# Importing Dataset1
dataset1 = pd.read_csv("covid.csv")
dataset1.head()  # returns first 5 rows

# Returns tuple of shape (Rows, columns)
print(dataset1.shape)

# Returns size of dataframe
print(dataset1.size)

# Information about Dataset1
# return concise summary of dataframe
dataset1.info()

# Importing Dataset2
dataset2 = pd.read_csv("covid.csv")
dataset2.head()  # return first 5 rows of dataset2

# Drop NewCases, NewDeaths, NewRecovered rows from dataset1

dataset1.drop(['NewCases', 'NewDeaths', 'NewRecovered'],
              axis=1, inplace=True)

# Select random set of values from dataset1
dataset1.sample(5)

import matplotlib.pyplot as py

# Import create_table Figure Factory
# Import create_table Figure Factory

from plotly.figure_factory import create_table
import plotly.graph_objects as go # Import plotly.graph_objects

colorscale = [[0, '#4d004c'], [.5, '#f2e5ff'], [1, '#ffffff']]
table = create_table(dataset1.head(15), colorscale=colorscale)
# py.plot(table) # Remove this line
table # Display the Plotly figure

import plotly.express as px

px.bar(dataset1.head(15), x = 'Country/Region',
       y = 'TotalCases',color = 'TotalCases',
       height = 500,hover_data = ['Country/Region', 'Continent'])

px.bar(dataset1.head(15), x = 'Country/Region', y = 'TotalCases',
       color = 'TotalDeaths', height = 500,
       hover_data = ['Country/Region', 'Continent'])

px.bar(dataset1.head(15), x = 'Country/Region', y = 'TotalCases',
       color = 'TotalDeaths', height = 500,
       hover_data = ['Country/Region', 'Continent'])

px.scatter(dataset1.head(57), x='Continent',y='TotalCases',
           hover_data=['Country/Region', 'Continent'],
           color='TotalCases', size='TotalCases', size_max=80, log_y=True)

px.scatter(dataset1.head(30), x='TotalCases', y= 'TotalDeaths',
           hover_data=['Country/Region', 'Continent'],
           color='TotalDeaths', size= 'TotalDeaths', size_max=80)

